### ISSUE TITLE
Connection refused on `logspout:stream`

### ISSUE THREAD

**Issue by saneef** [michaelshobbs/dokku-logspout#24]
I installed `dokku-logspout`, following steps [shown here](http://benradler.com/blog/2017/03/20/set-up-loggly-and-dokku-with-rails-logspout-and-syslog).

But when I do `dokku logspout:stream` I'm getting this error:

```bash
curl: (7) Failed to connect to 127.0.0.1 port 18000: Connection refused
```

Any tips on how to debug this?

**Comment by michaelshobbs** [comment]
Can you gist the output of `docker inspect logspout` and `dokku logspout:info`?

**Comment by saneef** [comment]
Here is the output of

`docker inspect logspout`  https://gist.github.com/saneef/0957b11d59c1b9a358c7b552ee91c9e2
`dokku logspout:info` https://gist.github.com/saneef/5e860643b6c8aedaf49c2443547b3a9b

**Comment by michaelshobbs** [comment]
Looks like this might be the issue: https://gist.github.com/saneef/0957b11d59c1b9a358c7b552ee91c9e2#file-gistfile1-json-L9-L10

What do you see from `docker logs logspout`?

**Comment by saneef** [comment]
This is what `docker logs logspout` is showing https://gist.github.com/saneef/2d3787b51e222d027a46c92275a45c93

Lot of `!! x509: certificate signed by unknown authority` erros. :(

**Comment by michaelshobbs** [comment]
That would be why `logspout:stream` isn't working for you. See gliderlabs/logspout#147 for a workaround
