### ISSUE TITLE
Help troubleshooting with loggly 

### ISSUE THREAD

**Issue by wootwoot1234** [michaelshobbs/dokku-logspout#28]
I've been trying to get dokku-logspout up and running with my new dokku build and I can't for the life of me get it working.  I could use some help with troubleshooting.

I followed this tutorial:

http://benradler.com/blog/2017/03/20/set-up-loggly-and-dokku-with-rails-logspout-and-syslog

Everything seems to be setup correctly and running but I'm not getting any logs.

    root@dokku-512mb-sfo2-01:~# dokku logspout:info
    =====> logspout status
    running
    =====> dokku-logspout config
    DOKKU_LOGSPOUT_IMAGE_VERSION=v3.1
    DOKKU_LOGSPOUT_PORT=18000
    DOKKU_LOGSPOUT_SYSLOG_SERVER=syslog://logs-01.loggly.com:514
    =====> dokku-logspout env
    SYSLOG_STRUCTURED_DATA=***MYCUSTOMERID***@41058

and: 

    root@dokku-512mb-sfo2-01:~# docker ps
    CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                   NAMES
    b182124372c2        gliderlabs/logspout:v3.1      "/bin/logspout sys..."   4 seconds ago       Up 3 seconds        127.0.0.1:514->80/tcp   logspout
    eac7ad8a1971        dokku/tools:latest            "/start worker"          17 minutes ago      Up 17 minutes                               tools.worker.1
    01ce6ed8818a        dokku/tools:latest            "/start web"             17 minutes ago      Up 17 minutes                               tools.web.1

any ideas?

**Comment by michaelshobbs** [comment]
Do you see output from `dokku logs <APP_NAME>`? What output do you see from `docker logs logspout`?

**Comment by wootwoot1234** [comment]
Thanks for the fast response.

Yes, I see my logs when I run `dokku logs <APP_NAME>`

and `docker logs logspout`:

    root@dokku-512mb-sfo2-01:~# docker logs logspout
    # logspout v3.1 by gliderlabs
    # adapters: tls raw syslog tcp udp
    # options : persist:/mnt/routes
    # jobs    : routes http[logs,routes]:80 pump
    # routes  :
    #   ADAPTER ADDRESS         CONTAINERS  SOURCES OPTIONS
    #   syslog  logs-01.loggly.com:514              map[]

**Comment by michaelshobbs** [comment]
I verified I could make this work following the tutorial you noted. Assuming the customer token is correct, the only other thing I can think to try is to destroy the logspout container and start it again.

example (ran `logspout:info` for comparison)
```
root@dokku:~/dokku# dokku logspout:info
=====> logspout status
       running
=====> dokku-logspout config
       DOKKU_LOGSPOUT_PORT=18000
       DOKKU_LOGSPOUT_IMAGE_VERSION=v3.1
       DOKKU_LOGSPOUT_SYSLOG_SERVER=syslog://logs-01.loggly.com:514
=====> dokku-logspout env
       SYSLOG_STRUCTURED_DATA=<TOKEN>@41058
root@dokku:~/dokku# dokku logspout:destroy
bf44dab46d66074249c67c9ac42a76677e168bf324617021ac076e2c61a93845
bf44dab46d66074249c67c9ac42a76677e168bf324617021ac076e2c61a93845
root@dokku:~/dokku# dokku logspout:start
root@dokku:~/dokku#
```

**Comment by wootwoot1234** [comment]
I just ran:

    root@dokku-512mb-sfo2-01:~# dokku logspout:destroy
    77fb8ed7ec9b3949e2ae40cc3d33a655a908660dfb58c5145de3df624b1fcf1d
    77fb8ed7ec9b3949e2ae40cc3d33a655a908660dfb58c5145de3df624b1fcf1d
    root@dokku-512mb-sfo2-01:~# dokku logspout:start
    root@dokku-512mb-sfo2-01:~# dokku logspout:info
    =====> logspout status
           running
    =====> dokku-logspout config
           DOKKU_LOGSPOUT_IMAGE_VERSION=v3.1
           DOKKU_LOGSPOUT_SYSLOG_SERVER=syslog://logs-01.loggly.com:514
           DOKKU_LOGSPOUT_PORT=514
    =====> dokku-logspout env
           SYSLOG_STRUCTURED_DATA=<MY TOKEN>@41058


Maybe I'm doing something wrong on loggly?

I got my teken from here:

https://MYUSERNAME.loggly.com/account/users/api/tokens

and going here to see if there are any logs:

https://MYUSERNAME.loggly.com/search

**Comment by wootwoot1234** [comment]
I figured it out!!!! 

You need to get the token from this page:

https://MYUSERNAME.loggly.com/tokens

This was confusing because there are at least 3 places that you can get tokens from.  I was grabbing the wrong one so you were right.  My token was wrong.  Thanks for the help and the great plugin!

**Comment by michaelshobbs** [comment]
From the sidebar on the api/tokens page:
> Your API token is used to provide access to Loggly's API for your user account. It is separate from your Source Setup Customer Tokens, which is used for sending data to Loggly.

You can find your token here:
https://.loggly.com/tokens

**Comment by michaelshobbs** [comment]
Ah cool you found it. Yeah definitely a confusing interface. Glad you got it sorted.

**Comment by wootwoot1234** [comment]
Looks like we figured out the issue at about the same time.  Yeah, I'm bad at reading subtext.  :/ 

Thanks again for the help.
