### ISSUE TITLE
Logspout not logging one-off containers

### ISSUE THREAD

**Issue by guidolodetti** [michaelshobbs/dokku-logspout#35]
Hi!

I run a cron task from a dokku app with the following command:

`dokku --rm run APP node FILE.js`

Unfortunately, logs are printed and I can see them, but Logspout seems not to be catching them. I already have other applications and all of them work correctly with Logspout!

Is it something related to the command `node FILE.js`?

Thanks!

*EDIT:* The same is if I do `dokku enter APP` and then `node FILE.js`!

**Comment by michaelshobbs** [comment]
Closing in favor of https://github.com/gliderlabs/logspout/issues/436. 

As a courtesy to the maintainers of open source projects, please do not open multiple issues across projects.

Thank you kindly.
