### ISSUE TITLE
How to persist the storage to store CA certificate?

### ISSUE THREAD

**Issue by leonardyhuang** [michaelshobbs/dokku-logspout#36]
Hi,

How to persist the storage to store CA certificate to communicate with Graylog using TLS?

Thanks.

**Comment by michaelshobbs** [comment]
Handling CA certs has not been a concern in my own use case. However, I'd certainly accept a pull request to do so.

**Comment by leonardyhuang** [comment]
Thanks for the prompt reply @michaelshobbs !

I'm not really familiar with docker, but this will be interesting to try.
And, I am closing this issue.
